/* globals workbox self */
workbox.setConfig({ debug: true })

workbox.core.setCacheNameDetails({
  prefix: 'keep-life',
  suffix: 'v2'
})

// Control all opened tabs ASAP
workbox.clientsClaim()

/**
 * Use precaching list generated by workbox in build process.
 * https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.precaching
 */
workbox.precaching.precacheAndRoute(self.__precacheManifest || []) // eslint-disable-line

/**
 * Register a navigation route.
 * https://developers.google.com/web/tools/workbox/modules/workbox-routing#how_to_register_a_navigation_route
 */
workbox.routing.registerNavigationRoute('/index.html')
// workbox.routing.registerNavigationRoute(workbox.precaching.getCacheKeyForURL('/index.html')) // TODO: for v4 only, WIP

workbox.routing.registerRoute(
  /^https:\/\/fonts.googleapis.com\//,
  new workbox.strategies.CacheFirst()
)

workbox.routing.registerRoute(
  /.*\.(?:png|jpg|jpeg|svg|gif|ico)/,
  new workbox.strategies.CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60
      })
    ]
  })
)

// TODO *WIP* need to check
workbox.routing.registerRoute(
  /^https:\/\/api.mapbox.com\//,
  new workbox.strategies.CacheFirst()
)

/**
 * Response to client after skipping waiting with MessageChannel
 */
self.addEventListener('message', (event) => { // eslint-disable-line
  const replyPort = event.ports[0]
  const message = event.data
  if (replyPort && message && message.type === 'skip-waiting') {
    event.waitUntil(
      self // eslint-disable-line
        .skipWaiting()
        .then(
          () => replyPort.postMessage({ error: null }),
          error => replyPort.postMessage({ error })
        )
    )
  }
})
